# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM node:24-slim AS base

COPY . /app
WORKDIR ${FOLDER}

ENV NODE_ENV=development

USER 1000:1000

EXPOSE 8080
ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
