# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.13-alpine

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

COPY --chown=1000:1000 . /app
WORKDIR ${FOLDER}

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Ensure installed tools can be executed out of the box
ENV UV_TOOL_BIN_DIR=/usr/local/bin

# Install Node.js and nodemon for easy watch mode with Python
USER root
RUN apk update \
    && apk add nodejs npm \
    && npm install -g nodemon

# Allow uv to use cache
RUN mkdir -p /.cache/uv && chown 1000:1000 /.cache /.cache/uv

USER 1000:1000

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

EXPOSE 8000
ENV PORT=8000
ENV HOST="0.0.0.0"

CMD ["/usr/local/bin/nodemon", \
    "--delay", "1", \
    "--watch", "pyproject.toml", \
    "--watch", ".venv/lib/*", \
    "--watch", ".venv/lib64/*", \
    "--exec", "uv run --isolated uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src --reload-exclude \".venv/**\"", \
    "--"]